CREATE TABLE TB_BRAND
(
    PK_ID VARCHAR2(32) PRIMARY KEY NOT NULL,
    FNAME VARCHAR2(80) NOT NULL,
    FNUMBER VARCHAR2(18) NOT NULL,
    FKMASTERID VARCHAR2(32) NOT NULL,
    BASESTATUS NUMBER(1) DEFAULT 1 NOT NULL,
    ICONURL VARCHAR2(120) NOT NULL
);
CREATE UNIQUE INDEX "TB_BRAND_FNUMBER_uindex" ON TB_BRAND (FNUMBER);
CREATE TABLE TB_CITY
(
    PK_ID VARCHAR2(32) PRIMARY KEY NOT NULL,
    FNAME VARCHAR2(40) NOT NULL,
    FNUMBER VARCHAR2(18) NOT NULL,
    CODE VARCHAR2(32) NOT NULL,
    FKPARENTID VARCHAR2(32) NOT NULL
);
CREATE TABLE TB_DELIVERY
(
    PK_ID VARCHAR2(32) PRIMARY KEY NOT NULL,
    FKMEMBERID VARCHAR2(32) NOT NULL,
    REGION VARCHAR2(120) NOT NULL,
    DETAILADDRESS VARCHAR2(255) NOT NULL,
    NIKENAME VARCHAR2(80) NOT NULL,
    MOBILE VARCHAR2(11) NOT NULL,
    PHONE VARCHAR2(12),
    BASESTATUS NUMBER(1) DEFAULT 1 NOT NULL
);
CREATE TABLE TB_GROUP
(
    PK_ID VARCHAR2(32) PRIMARY KEY NOT NULL,
    FKPARENTID VARCHAR2(32),
    FNUMBER VARCHAR2(18) NOT NULL,
    FNAME VARCHAR2(80) NOT NULL,
    ISLEAF NUMBER(1) DEFAULT 0 NOT NULL,
    ISROOT NUMBER(1) DEFAULT 0 NOT NULL
);
CREATE TABLE TB_LOG
(
    PK_ID VARCHAR2(32) PRIMARY KEY NOT NULL,
    FKMASTERNAME VARCHAR2(32) NOT NULL,
    TABLENAME VARCHAR2(80) NOT NULL,
    OPTYPE VARCHAR2(20) NOT NULL,
    CONTENTNOTE VARCHAR2(80) NOT NULL,
    PARAMS VARCHAR2(255) NOT NULL,
    OPTIME TIMESTAMP(6),
    MAINTAINTIME NUMBER(1)
);
CREATE TABLE TB_MASTER
(
    PK_ID VARCHAR2(32) PRIMARY KEY NOT NULL,
    FNAME VARCHAR2(80) NOT NULL,
    FPASSWORD VARCHAR2(80) NOT NULL,
    FSTATUS NUMBER(1) DEFAULT 1  NOT NULL,
    FKGROUPID VARCHAR2(32),
    FKROLEID VARCHAR2(32)
);
CREATE UNIQUE INDEX TB_MASTER_FNAME_UINDEX ON TB_MASTER (LOGINNAME);
CREATE TABLE TB_MEMBER
(
    PK_ID VARCHAR2(32) PRIMARY KEY NOT NULL,
    LOGINNAME VARCHAR2(80) NOT NULL,
    PASSWORD VARCHAR2(80) NOT NULL,
    NIKENAME VARCHAR2(120),
    BASESTATUS NUMBER(1) DEFAULT 1 NOT NULL
);
CREATE UNIQUE INDEX "TB_MEMBER_LOGINNAME_uindex" ON TB_MEMBER (LOGINNAME);
CREATE TABLE TB_ORDER
(
    PK_ID VARCHAR2(32) PRIMARY KEY NOT NULL,
    ADDTIME TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
    PAYTIME TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
    BASESTATUS NUMBER(1) DEFAULT 0 NOT NULL,
    PAYSTATUS NUMBER(1) DEFAULT 0 NOT NULL,
    STATUS NUMBER(1) DEFAULT 0 NOT NULL,
    F2STATUS NUMBER(1) DEFAULT 0 NOT NULL,
    FKMASTERID VARCHAR2(32) NOT NULL,
    FKACCOUNTID VARCHAR2(32) NOT NULL,
    FKGOODSID VARCHAR2(32) NOT NULL
);
CREATE TABLE TB_ORDERDELIVERYINFO
(
    PK_ID VARCHAR2(32) PRIMARY KEY NOT NULL,
    FKDELIVERYID VARCHAR2(32) NOT NULL,
    BASESTATUS NUMBER(1) DEFAULT 1

);
CREATE TABLE TB_ORDERPAYINFO
(
    PK_ID VARCHAR2(32) PRIMARY KEY NOT NULL,
    FKPAYTYPEID VARCHAR2(32) NOT NULL,
    PAYTIME TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
    GOODSAMOUNT NUMBER(13,8) DEFAULT 0.00000000 NOT NULL,
    PAYAMOUNT NUMBER(13,8) DEFAULT 0.00000000 NOT NULL,
    FREIGHT NUMBER(13,8) DEFAULT 0.00000000 NOT NULL,
    DISCOUNT NUMBER(13,8) DEFAULT 0.00000000 NOT NULL,
    COUPON NUMBER(13,8) DEFAULT 0.00000000 NOT NULL,
    PAYDISCOUNT NUMBER(13,8) DEFAULT 0.00000000 NOT NULL
);
CREATE TABLE TB_PERMISSION
(
    PK_ID VARCHAR2(32) PRIMARY KEY NOT NULL,
    FNUMBER VARCHAR2(18) NOT NULL,
    FNAME VARCHAR2(18) NOT NULL,
    BASESTATUS NUMBER(1) DEFAULT 1 NOT NULL
);
CREATE TABLE TB_PRIVILEGE
(
    PK_ID VARCHAR2(32) PRIMARY KEY NOT NULL,
    PRIVILEGEMASTER VARCHAR2(80) NOT NULL,
    PRIVILEGEMASTERVALUE VARCHAR2(32) NOT NULL,
    PRIVILEGEACCESS VARCHAR2(80) NOT NULL,
    PRIVILEGEACCESSVALUE VARCHAR2(32) NOT NULL,
    PRIVILEGEOPERATION NUMBER(1) NOT NULL
);
CREATE TABLE TB_ROLE
(
    PK_ID VARCHAR2(32) PRIMARY KEY NOT NULL,
    FNAME VARCHAR2(18) NOT NULL,
    FNUMBER VARCHAR2(18) NOT NULL,
    BASESTATUS NUMBER(1) DEFAULT 1 NOT NULL
);
CREATE TABLE TB_TOKENHISTORY
(
    PK_ID VARCHAR2(32) PRIMARY KEY NOT NULL,
    ADDTIME TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
    ACCESSTOKEN VARCHAR2(255) NOT NULL,
    FKMASTERID VARCHAR2(32) NOT NULL,
    LOGINIP VARCHAR2(18) NOT NULL
);
